In [1]:
import pandas as pd
import numpy as np

In [24]:
l = list()
a = np.asarray([[11,12,13,14],[21,22,23,24],[31,32,33,34],[41,42,43,44]])
a

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [28]:
np.random.shuffle(a)
a

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [26]:
b = np.ndarray((1,))

In [10]:
b.shape

(1,)

In [22]:
b =a 
b

array([[21, 22, 23, 24],
       [11, 12, 13, 14]])

In [20]:
b

array([[11, 12, 13, 14],
       [21, 22, 23, 24]])

In [23]:
np.random.shuffle(b)
b

array([[21, 22, 23, 24],
       [11, 12, 13, 14]])